---
title: "concentration fitting from different samples"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(MASS)
library(goftest)

```

```{r}
# Organoids
sample_one=c(0.18,1.28,0.18,1.39,0.38,0.55,4.91,0.18,1.14,0.33,0.34,1.89,2.60,0.90,0.26,0.39,16.16,0.71,1.40,0.14,1.10,0.09,0.37,2.60,0.68,0.07,0.27,0.29,0.46,0.44,3.04,0.67,0.30)

set.seed(456)
fit=fitdistr(sample_one,"gamma")
fit
ks.test(sample_one_nodup,"pgamma",shape=fit$estimate[[1]],rate=fit$estimate[[2]])
cvm.test(sample_one,null="pgamma",shape=fit$estimate[[1]],rate=fit$estimate[[2]])


{h=hist(sample_one,breaks=seq(0,20,0.2),plot=FALSE)
h$density = (h$counts/sum(h$counts))/0.2
plot(h,freq=FALSE,xlab = "concentration",main="Distribution of concentrations in an organoids sample")
curve(dgamma(x, fit$estimate[[1]],fit$estimate[[2]]), col="red", lwd=2, add=T)}

```


```{r}
# human plasma
sample_two=c(978.9264,860.9853,303.3246,146.7005,145.9645,117.2636,116.6943,94.9210,84.7311,74.4076,69.9736,60.0977,59.2102,55.5346,52.5725,52.0129,34.9681,32.3788,30.1553,25.3216,24.7836,21.1557,19.5555,17.7920,17.0074,14.9654,14.7065,12.7426,12.6340,10.1299,9.5584,8.8277,8.3729,8.1242,5.5581,4.6109,3.9471,2.3517,1.8874)


hist(sample_two,breaks=seq(0,1000,8))

set.seed(789)
fit=fitdistr(sample_two,"gamma")
fit

ks.test(sample_two,"pgamma",shape=fit$estimate[[1]],rate=fit$estimate[[2]])
cvm.test(sample_two,null="pgamma",shape=fit$estimate[[1]],rate=fit$estimate[[2]])


{h=hist(sample_two,breaks=seq(0,1000,8),plot=FALSE)
h$density = (h$counts/sum(h$counts))/8
plot(h,freq=FALSE,ylim=c(0,0.03),xlab = "concentration",main="Distribution of concentrations in a human plasma sample")
curve(dgamma(x, fit$estimate[[1]],fit$estimate[[2]]), col="red", lwd=2, add=T)}


```


```{r}
## cerebellum
sample_three=c(37.3,48,13.8,20.9,76,14.6,101.4,9.5,6.1,1.7,85.3,28.6,20.6,3.8,3.2,89.9,8.1,7.6,10.3,4.6,13,2.7,70.6,3.4,2.2,56.6,2.9)*(1e-3)

hist(sample_three,breaks=seq(0,0.11,0.01))

set.seed(78)
fit=fitdistr(sample_three,"gamma")
fit

ks.test(sample_three,"pgamma",shape=fit$estimate[[1]],rate=fit$estimate[[2]])
cvm.test(sample_three,null="pgamma",shape=fit$estimate[[1]],rate=fit$estimate[[2]])

{h=hist(sample_three,breaks=seq(0,0.11,0.01),plot=FALSE)
h$density = (h$counts/sum(h$counts))/0.01
plot(h,freq=FALSE,xlab = "concentration",main="Distribution of concentrations in a cerebellum sample")
curve(dgamma(x, fit$estimate[[1]],fit$estimate[[2]]), col="red", lwd=2, add=T)}
```

```{r}
### cells

sample_four=c(11.2,1.4,1.3,1.3,2.5,5.5,2.5,11.6,2.3,0.5,8.5,1.4,1,1.7,0.8,1.9,12.5,3.5,1.2,10.7,12.7,6.2,2.2,2,15.5,3.7,6,1.7,1.2,28.5,1,1.5,2,15.5,4.4)

hist(sample_four,breaks=seq(0,30,2))

sample_four_nodup=sample_four[which(duplicated(sample_four)==FALSE)]

## gamma
set.seed(29)
fit=fitdistr(sample_four,"gamma")
fit
ks.test(sample_four_nodup,"pgamma",shape=fit$estimate[[1]],
        rate=fit$estimate[[2]])

cvm.test(sample_four,null="pgamma",shape=fit$estimate[[1]],
         rate=fit$estimate[[2]])


{h=hist(sample_four,breaks=seq(0,30,2),plot=FALSE)
h$density = (h$counts/sum(h$counts))/2
plot(h,freq=FALSE,xlab = "concentration",main="Distribution of concentrations in a cells sample")
curve(dgamma(x, fit$estimate[[1]],fit$estimate[[2]]), col="red", lwd=2, add=T)}
```

```{r}
### Amniotic fluid 

sample_five=c(86.4,224.6,254.1,72.4,7.2,37.4,34.2,33.6,10430.1,29.6,59.4,70.2,124.3,11.3,74.9,30.6,70.6,9.5,61.2,7.3,113.7,19.3,42.5,95.9,146.4,108.9,13.2,26.2,83.6,64,8.7,5.5,41.2,1475.7,76.6)*(1e-3)

hist(sample_five,breaks=seq(0,11,0.05))

ks.test(sample_five,"pgamma",shape=0.5,rate=5)
cvm.test(sample_five,null="pgamma",shape=0.5,rate=5)

{h=hist(sample_five,breaks=seq(0,11,0.05),plot=FALSE)
h$density = (h$counts/sum(h$counts))/0.05
plot(h,freq=FALSE,xlab = "concentration",main="Distribution of concentrations in an amniotic fluid sample")
curve(dgamma(x, 0.5,5), col="red", lwd=2, add=T)}

```

```{r}
### fly brain

sample_six=c(0.4878,0.4188,0.3302,0.3211,0.3129,0.2004,0.1893,0.1889,0.1886,0.1591,0.1467,0.1373,0.1350,0.1347,0.1306,0.1012,0.0981,0.0961,0.0811,0.0599,0.0473,0.0346,0.0308,0.0297,0.0293,0.0229)

hist(sample_six,breaks=seq(0,0.5,0.01))

fit=fitdistr(sample_six,"gamma")
fit
ks.test(sample_six,"pgamma",shape=fit$estimate[[1]],rate=fit$estimate[[2]])
cvm.test(sample_six,null="pgamma",shape=fit$estimate[[1]],rate=fit$estimate[[2]])


{h=hist(sample_six,breaks=seq(0,0.5,0.01),plot=FALSE)
h$density = (h$counts/sum(h$counts))/0.01
plot(h,freq=FALSE,xlab = "concentration",main="Distribution of concentrations in a fly-brain sample")
curve(dgamma(x, fit$estimate[[1]],fit$estimate[[2]]), col="red", lwd=2, add=T)}
```

```{r}
## cell media

sample_seven=c(64.8844,26.9595,15.9071,5.1314,4.6596,3.1125,2.5097,2.4476,2.1501,2.0127,1.9805,1.6115,1.3799,1.2389,1.0142,0.8250,0.7311,0.4876,0.4120,0.3364,0.1032)

hist(sample_seven,breaks=seq(0,65,1))


fit=fitdistr(sample_seven,"gamma")
fit
ks.test(sample_seven,"pgamma",shape=fit$estimate[[1]],rate=0.2)
cvm.test(sample_seven,null="pgamma",shape=fit$estimate[[1]],rate=0.2)

{h=hist(sample_seven,breaks=seq(0,65,1),plot=FALSE)
h$density = (h$counts/sum(h$counts))
plot(h,freq=FALSE,xlab = "concentration",main="Distribution of concentrations in a cell-media sample")
curve(dgamma(x, fit$estimate[[1]],0.2), col="red", lwd=2, add=T)}
```


```{r}
## final test and summary

# Organoids
sample_one=c(0.18,1.28,0.18,1.39,0.38,0.55,4.91,0.18,1.14,0.33,0.34,1.89,2.60,0.90,0.26,0.39,16.16,0.71,1.40,0.14,1.10,0.09,0.37,2.60,0.68,0.07,0.27,0.29,0.46,0.44,3.04,0.67,0.30)

sample_one_nodup=sample_one[which(duplicated(sample_one)=="FALSE")]

ks.test(sample_one_nodup,"pgamma",shape=0.73,rate=0.52)
#p-value = 0.2498
cvm.test(sample_one,null="pgamma",shape=0.73,rate=0.52)
#p-value = 0.1324

# human plasma
sample_two=c(978.9264,860.9853,303.3246,146.7005,145.9645,117.2636,116.6943,94.9210,84.7311,74.4076,69.9736,60.0977,59.2102,55.5346,52.5725,52.0129,34.9681,32.3788,30.1553,25.3216,24.7836,21.1557,19.5555,17.7920,17.0074,14.9654,14.7065,12.7426,12.6340,10.1299,9.5584,8.8277,8.3729,8.1242,5.5581,4.6109,3.9471,2.3517,1.8874)

ks.test(sample_two,"pgamma",shape=0.55,rate=0.01)
#p-value = 0.3375
cvm.test(sample_two,null="pgamma",shape=0.55,rate=0.01)
#p-value = 0.4226


## cerebellum
sample_three=c(37.3,48,13.8,20.9,76,14.6,101.4,9.5,6.1,1.7,85.3,28.6,20.6,3.8,3.2,89.9,8.1,7.6,10.3,4.6,13,2.7,70.6,3.4,2.2,56.6,2.9)*(1e-3)

ks.test(sample_three,"pgamma",shape=0.82,rate=29.94)
#p-value = 0.5792
cvm.test(sample_three,null="pgamma",shape=0.82,rate=29.94)
#p-value = 0.4604

### cells
sample_four=c(11.2,1.4,1.3,1.3,2.5,5.5,2.5,11.6,2.3,0.5,8.5,1.4,1,1.7,0.8,1.9,12.5,3.5,1.2,10.7,12.7,6.2,2.2,2,15.5,3.7,6,1.7,1.2,28.5,1,1.5,2,15.5,4.4)

sample_four_nodup=sample_four[which(duplicated(sample_four)==FALSE)]

ks.test(sample_four_nodup,"pgamma",shape=1.08,rate=0.2)
#p-value = 0.7393
cvm.test(sample_four,null="pgamma",shape=1.08,rate=0.2)
#p-value = 0.1504

### Amniotic fluid 
sample_five=c(86.4,224.6,254.1,72.4,7.2,37.4,34.2,33.6,10430.1,29.6,59.4,70.2,124.3,11.3,74.9,30.6,70.6,9.5,61.2,7.3,113.7,19.3,42.5,95.9,146.4,108.9,13.2,26.2,83.6,64,8.7,5.5,41.2,1475.7,76.6)*(1e-3)

ks.test(sample_five,"pgamma",shape=0.5,rate=5)
#p-value = 0.1586
cvm.test(sample_five,null="pgamma",shape=0.5,rate=5)
#p-value = 0.1231

### fly brain

sample_six=c(0.4878,0.4188,0.3302,0.3211,0.3129,0.2004,0.1893,0.1889,0.1886,0.1591,0.1467,0.1373,0.1350,0.1347,0.1306,0.1012,0.0981,0.0961,0.0811,0.0599,0.0473,0.0346,0.0308,0.0297,0.0293,0.0229)

ks.test(sample_six,"pgamma",shape=1.69,rate=10.67)
#p-value = 0.9523
cvm.test(sample_six,null="pgamma",shape=1.69,rate=10.67)
#p-value = 0.9057

## cell media
sample_seven=c(64.8844,26.9595,15.9071,5.1314,4.6596,3.1125,2.5097,2.4476,2.1501,2.0127,1.9805,1.6115,1.3799,1.2389,1.0142,0.8250,0.7311,0.4876,0.4120,0.3364,0.1032)

ks.test(sample_seven,"pgamma",shape=0.52,rate=0.2)
#p-value = 0.212
cvm.test(sample_seven,null="pgamma",shape=0.52,rate=0.2)
#p-value = 0.1512

```

